<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">

	<title>Namespace DSchoenbauer\Exception\Platform</title>

	<link rel="stylesheet" href="resources/style.css?e99947befd7bf673c6b43ff75e9e0f170c88a60e">

</head>

<body>
<div id="left">
	<div id="menu">
		<a href="index.html" title="Overview"><span>Overview</span></a>


		<div id="groups">
				<h3>Namespaces</h3>
			<ul>
				<li class="active">
					<a href="namespace-DSchoenbauer.html">
						DSchoenbauer<span></span>
					</a>

						<ul>
				<li class="active">
					<a href="namespace-DSchoenbauer.Exception.html">
						Exception<span></span>
					</a>

						<ul>
				<li>
					<a href="namespace-DSchoenbauer.Exception.Http.html">
						Http<span></span>
					</a>

						<ul>
				<li>
					<a href="namespace-DSchoenbauer.Exception.Http.ClientError.html">
						ClientError					</a>

						</li>
				<li>
					<a href="namespace-DSchoenbauer.Exception.Http.ServerError.html">
						ServerError					</a>

						</li>
							</ul></li>
				<li class="active">
					<a href="namespace-DSchoenbauer.Exception.Platform.html">
						Platform					</a>

						</li>
							</ul></li></ul></li>
			</ul>
		</div>

		<hr>


		<div id="elements">



			<h3>Exceptions</h3>
			<ul>
				<li><a href="class-DSchoenbauer.Exception.Platform.BadFunctionCallException.html">BadFunctionCallException</a></li>
				<li><a href="class-DSchoenbauer.Exception.Platform.BadMethodCallException.html">BadMethodCallException</a></li>
				<li><a href="class-DSchoenbauer.Exception.Platform.DomainException.html">DomainException</a></li>
				<li><a href="class-DSchoenbauer.Exception.Platform.Exception.html">Exception</a></li>
				<li><a href="class-DSchoenbauer.Exception.Platform.InvalidArgumentException.html">InvalidArgumentException</a></li>
				<li><a href="class-DSchoenbauer.Exception.Platform.LengthException.html">LengthException</a></li>
				<li><a href="class-DSchoenbauer.Exception.Platform.LogicException.html">LogicException</a></li>
				<li><a href="class-DSchoenbauer.Exception.Platform.OutOfBoundsException.html">OutOfBoundsException</a></li>
				<li><a href="class-DSchoenbauer.Exception.Platform.OutOfRangeException.html">OutOfRangeException</a></li>
				<li><a href="class-DSchoenbauer.Exception.Platform.OverflowException.html">OverflowException</a></li>
				<li><a href="class-DSchoenbauer.Exception.Platform.RangeException.html">RangeException</a></li>
				<li><a href="class-DSchoenbauer.Exception.Platform.RuntimeException.html">RuntimeException</a></li>
				<li><a href="class-DSchoenbauer.Exception.Platform.UnderflowException.html">UnderflowException</a></li>
				<li><a href="class-DSchoenbauer.Exception.Platform.UnexpectedValueException.html">UnexpectedValueException</a></li>
			</ul>


		</div>
	</div>
</div>

<div id="splitter"></div>

<div id="right">
<div id="rightInner">
	<form id="search">
		<input type="hidden" name="cx" value="">
		<input type="hidden" name="ie" value="UTF-8">
		<input type="text" name="q" class="text" placeholder="Search">
	</form>

	<div id="navigation">
		<ul>
			<li>
				<a href="index.html" title="Overview"><span>Overview</span></a>
			</li>
			<li class="active">
<span>Namespace</span>			</li>
			<li>
<span>Class</span>			</li>
		</ul>
		<ul>
		</ul>
		<ul>
		</ul>
	</div>

<div id="content" class="namespace">
	<h1>Namespace <a href="namespace-DSchoenbauer.html">DSchoenbauer</a>\<a href="namespace-DSchoenbauer.Exception.html">Exception</a>\Platform</h1>






<table class="summary" id="exceptions">
<caption>Exceptions summary</caption>
<tr>
	<td class="name"><a href="class-DSchoenbauer.Exception.Platform.BadFunctionCallException.html">BadFunctionCallException</a></td>
	<td>Exception thrown if a callback refers to an undefined function or if some arguments are missing.</td>
</tr>
<tr>
	<td class="name"><a href="class-DSchoenbauer.Exception.Platform.BadMethodCallException.html">BadMethodCallException</a></td>
	<td>Exception thrown if a callback refers to an undefined method or if some arguments are missing.</td>
</tr>
<tr>
	<td class="name"><a href="class-DSchoenbauer.Exception.Platform.DomainException.html">DomainException</a></td>
	<td><p>Domain means data domain here. That is a DomainException shall be through whenever a value does not adhere to a defined valid data domain. Examples:
- 0 is not a in the domain for division.
- Foo is not in the domain for weekdays.
- Apple is not in the domain for months</p></td>
</tr>
<tr>
	<td class="name"><a href="class-DSchoenbauer.Exception.Platform.Exception.html">Exception</a></td>
	<td>Exception is the base class for all Exceptions</td>
</tr>
<tr>
	<td class="name"><a href="class-DSchoenbauer.Exception.Platform.InvalidArgumentException.html">InvalidArgumentException</a></td>
	<td>Exception thrown if an argument is not of the expected type.</td>
</tr>
<tr>
	<td class="name"><a href="class-DSchoenbauer.Exception.Platform.LengthException.html">LengthException</a></td>
	<td>Exception thrown if a length is invalid.</td>
</tr>
<tr>
	<td class="name"><a href="class-DSchoenbauer.Exception.Platform.LogicException.html">LogicException</a></td>
	<td><p>Exception that represents error in the program logic.
This kind of exception should lead directly to a fix in your code.</p></td>
</tr>
<tr>
	<td class="name"><a href="class-DSchoenbauer.Exception.Platform.OutOfBoundsException.html">OutOfBoundsException</a></td>
	<td>Exception thrown if a value is not a valid key. This represents errors that cannot be detected at compile time.</td>
</tr>
<tr>
	<td class="name"><a href="class-DSchoenbauer.Exception.Platform.OutOfRangeException.html">OutOfRangeException</a></td>
	<td>Exception thrown when an illegal index was requested. This represents errors that should be detected at compile time.</td>
</tr>
<tr>
	<td class="name"><a href="class-DSchoenbauer.Exception.Platform.OverflowException.html">OverflowException</a></td>
	<td>Exception thrown when adding an element to a full container.</td>
</tr>
<tr>
	<td class="name"><a href="class-DSchoenbauer.Exception.Platform.RangeException.html">RangeException</a></td>
	<td><p>Exception thrown to indicate range errors during program execution.
Normally this means there was an arithmetic error other than under/overflow.
This is the runtime version of DomainException.</p></td>
</tr>
<tr>
	<td class="name"><a href="class-DSchoenbauer.Exception.Platform.RuntimeException.html">RuntimeException</a></td>
	<td>Exception thrown if an error which can only be found on runtime occurs.</td>
</tr>
<tr>
	<td class="name"><a href="class-DSchoenbauer.Exception.Platform.UnderflowException.html">UnderflowException</a></td>
	<td><p>Exception thrown when performing an invalid operation on an empty container,
such as removing an element.</p></td>
</tr>
<tr>
	<td class="name"><a href="class-DSchoenbauer.Exception.Platform.UnexpectedValueException.html">UnexpectedValueException</a></td>
	<td><p>Exception thrown if a value does not match with a set of values.
Typically this happens when a function calls another function and expects the
return value to be of a certain type or value not including arithmetic or
buffer related errors.</p></td>
</tr>
</table>


</div>

	<div id="footer">
		 API documentation generated by <a href="http://apigen.org">ApiGen</a>
	</div>
</div>
</div>
<script src="resources/combined.js?35e7b6810bdb963990310abd22863f284f6717aa"></script>
<script src="elementlist.js?35b0fd8e88682c3f7020e129e0f0586e66bd86b5"></script>
</body>
</html>
